app: sendmemail
tenant: fanciestw

service:
  name: sendMeMail

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: src.app.email
    events:
      - http:
          method: post
          path: email
