
tenant: fanciestw
app: sendmemail

service:
  name: sendMeMail

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  sendmemail:
    handler: src.app.email
    events:
      - http:
          method: post
          path: email
